[package]
name = "leo-eclipse-fraction-calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
marlu = {version = "0.9.1", default-features = false}
measurements = "0.11.0"
